<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="Microsoft.Office.Interop.Excel" Version="16.0.18925.20022" />
    <PackageVersion Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
    <PackageVersion Include="Microsoft.Office.Interop.PowerPoint" Version="15.0.4420.1018" />
    <PackageVersion Include="Ipercube.Office.Interop.Core" Version="15.0.1" />
  </ItemGroup>
</Project>
