<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>OMNIX.Core.Tests</AssemblyName>
    <RootNamespace>OMNIX.Core.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\OMNIX.Core\OMNIX.Core.csproj" />
  </ItemGroup>
</Project>
