<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OMNIX.Word</AssemblyName>
    <RootNamespace>OMNIX.Word</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OMNIX.Core\OMNIX.Core.csproj" />
    <PackageReference Include="Microsoft.Office.Interop.Word" />
    <PackageReference Include="Ipercube.Office.Interop.Core" />
  </ItemGroup>
</Project>
