<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OMNIX.Excel</AssemblyName>
    <RootNamespace>OMNIX.Excel</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OMNIX.Core\OMNIX.Core.csproj" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" />
    <PackageReference Include="Ipercube.Office.Interop.Core" />
  </ItemGroup>
  <ItemGroup>
    <Reference Update="Microsoft.Office.Interop.Excel">
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <Private>false</Private>
    </Reference>
    <Reference Update="Office">
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
