# OMNIX canonical real-machine evidence runner.
#
# This wrapper prevents stale PASS reports from being replayed against another build. It executes
# the real acceptance harness first, requires a freshly generated report, and only then adds a
# sanitized EvidenceBinding. The binding is created only after the installed OMNIX-build-identity
# proves the exact source commit and the hashes of Core + all three Office host assemblies.
#
# It never disables security, changes networking, restarts Windows, or alters Office Trust Center.
# Restart testing remains a two-phase user-driven process.

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [ValidateSet('FullOfficeE2E','LocalOffline','Provider','RestartBefore','RestartAfter')]
    [string]$Kind,
    [string]$InstallerPath,
    [string]$ExpectedInstallerSha256,
    [string]$InstallDir = "$env:LOCALAPPDATA\Programs\OMNIX",
    [string]$CorePath,
    [string]$SourceCommit,
    [string]$OutputPath,
    [string]$RestartStatePath = "$env:LOCALAPPDATA\OMNIX\logs\restart-persistence-state.json",
    [string]$RestartBindingStatePath = "$env:LOCALAPPDATA\OMNIX\logs\restart-evidence-binding-state.json",
    [int]$TimeoutSeconds = 45
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$bindingScript = Join-Path $scriptDir 'real-evidence-binding.ps1'
if (-not (Test-Path -LiteralPath $bindingScript -PathType Leaf)) {
    throw "Real evidence binding helper missing: $bindingScript"
}
. $bindingScript

if ([string]::IsNullOrWhiteSpace($CorePath)) {
    $CorePath = Join-Path $InstallDir 'OMNIX.Core.dll'
}

function Get-DefaultOutput([string]$kind) {
    $logRoot = Join-Path $env:LOCALAPPDATA 'OMNIX\logs'
    switch ($kind) {
        'FullOfficeE2E' { return (Join-Path $logRoot 'full-office-e2e.json') }
        'LocalOffline'  { return (Join-Path $logRoot 'local-ai-offline-acceptance.json') }
        'Provider'      { return (Join-Path $logRoot 'provider-acceptance.json') }
        'RestartAfter'  { return (Join-Path $logRoot 'real-office-restart-acceptance.json') }
        default         { return (Join-Path $logRoot 'real-office-restart-acceptance.json') }
    }
}

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Get-DefaultOutput $Kind
}

function Read-Json([string]$path,[string]$label) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "$label not found: $path" }
    try { return Get-Content -LiteralPath $path -Raw | ConvertFrom-Json }
    catch { throw "$label is not valid JSON: $path - $($_.Exception.Message)" }
}

function Assert-FreshTimestamp($report,[DateTime]$startedUtc,[string]$label) {
    $parsed = [DateTime]::MinValue
    if ([string]::IsNullOrWhiteSpace([string]$report.TimestampUtc) -or
        -not [DateTime]::TryParse([string]$report.TimestampUtc,[ref]$parsed)) {
        throw "$label does not contain a valid TimestampUtc."
    }
    $parsed = $parsed.ToUniversalTime()
    if ($parsed -lt $startedUtc.AddMinutes(-2)) {
        throw "$label was not freshly generated by this invocation."
    }
    if ($parsed -gt [DateTime]::UtcNow.AddMinutes(10)) {
        throw "$label TimestampUtc is implausibly in the future."
    }
}

function Save-BoundReport([string]$path,$binding,[DateTime]$startedUtc,[string]$label) {
    $report = Read-Json $path $label
    Assert-FreshTimestamp $report $startedUtc $label
    $report | Add-Member -NotePropertyName EvidenceBinding -NotePropertyValue ([pscustomobject]$binding) -Force
    $report | ConvertTo-Json -Depth 15 | Set-Content -LiteralPath $path -Encoding UTF8
    return $report
}

function Invoke-Child([string]$scriptName,[string[]]$arguments,[string]$label) {
    $path = Join-Path $scriptDir $scriptName
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "$label script missing: $path" }

    $powershell = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    if (-not (Test-Path -LiteralPath $powershell -PathType Leaf)) { $powershell = 'powershell.exe' }
    $args = @('-NoProfile','-File',$path) + $arguments

    # The call operator preserves argument boundaries, including paths with spaces. Start-Process
    # -ArgumentList joins arguments into one command-line string and can corrupt unquoted paths.
    & $powershell @args
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) { throw "$label failed with exit code $exitCode." }
}

function Remove-ReportIfPresent([string]$path) {
    if (Test-Path -LiteralPath $path -PathType Leaf) { Remove-Item -LiteralPath $path -Force }
}

function Binding-Summary($binding,[string]$kind,[string]$installerSha=$null,[string]$nextAction=$null) {
    $row = [ordered]@{
        TestId = 'BOUND-REAL-ACCEPTANCE-001'
        Kind = $kind
        SourceCommit = $binding.SourceCommit
        CoreSha256 = $binding.CoreSha256
        PayloadIdentitySha256 = $binding.PayloadIdentitySha256
        PrimaryAssembliesValidated = [bool]$binding.PrimaryAssembliesValidated
        OverallPass = $true
    }
    if (-not [string]::IsNullOrWhiteSpace($installerSha)) { $row.InstallerSha256 = $installerSha }
    if (-not [string]::IsNullOrWhiteSpace($nextAction)) { $row.NextAction = $nextAction }
    return [pscustomobject]$row
}

$startedUtc = [DateTime]::UtcNow

if ($Kind -eq 'FullOfficeE2E') {
    if ([string]::IsNullOrWhiteSpace($InstallerPath)) { throw 'FullOfficeE2E requires -InstallerPath.' }
    if ([string]::IsNullOrWhiteSpace($ExpectedInstallerSha256)) { throw 'FullOfficeE2E requires -ExpectedInstallerSha256.' }
    $expected = $ExpectedInstallerSha256.Trim().ToLowerInvariant()
    if ($expected -notmatch '^[0-9a-f]{64}$') { throw 'ExpectedInstallerSha256 must be 64 hexadecimal characters.' }
    if (-not (Test-Path -LiteralPath $InstallerPath -PathType Leaf)) { throw "Installer not found: $InstallerPath" }
    $actualInstaller = (Get-FileHash -Algorithm SHA256 -LiteralPath $InstallerPath).Hash.ToLowerInvariant()
    if ($actualInstaller -ne $expected) { throw "Installer SHA256 mismatch before E2E. Expected=$expected Actual=$actualInstaller" }

    Remove-ReportIfPresent $OutputPath
    $logDir = Split-Path -Parent $OutputPath
    if ($logDir) { New-Item -ItemType Directory -Force -Path $logDir | Out-Null }
    foreach ($name in @('real-office-acceptance.json','real-office-ui-acceptance.json','taskpane-lifecycle-real-acceptance.json')) {
        Remove-ReportIfPresent (Join-Path $logDir $name)
    }

    Invoke-Child 'full-office-e2e.ps1' @(
        '-InstallerPath',$InstallerPath,
        '-ExpectedInstallerSha256',$expected,
        '-InstallDir',$InstallDir,
        '-OutputPath',$OutputPath
    ) 'Full Office E2E'

    # New-OmnixEvidenceBinding validates the installed build identity and all four primary assemblies.
    $binding = New-OmnixEvidenceBinding -CorePath $CorePath -SourceCommit $SourceCommit
    $office = Save-BoundReport $OutputPath $binding $startedUtc 'Full Office E2E report'
    if ([string]$office.Installer.Sha256 -ne $expected -or -not [bool]$office.Installer.HashMatchedExpected) {
        throw 'Full Office E2E report is not bound to the exact installer SHA256.'
    }

    foreach ($row in @(
        @{ Path=(Join-Path $logDir 'real-office-acceptance.json'); Label='Office persistence report' },
        @{ Path=(Join-Path $logDir 'real-office-ui-acceptance.json'); Label='Office UI report' },
        @{ Path=(Join-Path $logDir 'taskpane-lifecycle-real-acceptance.json'); Label='Task-pane lifecycle report' }
    )) {
        [void](Save-BoundReport $row.Path $binding $startedUtc $row.Label)
    }

    Binding-Summary $binding $Kind $expected | ConvertTo-Json -Depth 5
    exit 0
}

if ($Kind -eq 'LocalOffline') {
    Remove-ReportIfPresent $OutputPath
    Invoke-Child 'local-offline-acceptance.ps1' @('-OutputPath',$OutputPath,'-TimeoutSeconds',[string]$TimeoutSeconds) 'Local offline acceptance'
    $binding = New-OmnixEvidenceBinding -CorePath $CorePath -SourceCommit $SourceCommit
    [void](Save-BoundReport $OutputPath $binding $startedUtc 'Local offline report')
    Binding-Summary $binding $Kind | ConvertTo-Json -Depth 5
    exit 0
}

if ($Kind -eq 'Provider') {
    Remove-ReportIfPresent $OutputPath
    Invoke-Child 'provider-acceptance.ps1' @('-OutputPath',$OutputPath,'-TimeoutSeconds',[string]$TimeoutSeconds) 'Provider acceptance'
    $binding = New-OmnixEvidenceBinding -CorePath $CorePath -SourceCommit $SourceCommit
    [void](Save-BoundReport $OutputPath $binding $startedUtc 'Provider report')
    Binding-Summary $binding $Kind | ConvertTo-Json -Depth 5
    exit 0
}

if ($Kind -eq 'RestartBefore') {
    $binding = New-OmnixEvidenceBinding -CorePath $CorePath -SourceCommit $SourceCommit
    $bindingDir = Split-Path -Parent $RestartBindingStatePath
    if ($bindingDir) { New-Item -ItemType Directory -Force -Path $bindingDir | Out-Null }
    if (Test-Path -LiteralPath $RestartBindingStatePath -PathType Leaf) { Remove-Item -LiteralPath $RestartBindingStatePath -Force }

    Invoke-Child 'reboot-persistence-acceptance.ps1' @(
        '-Phase','BeforeRestart',
        '-StatePath',$RestartStatePath,
        '-OutputPath',$OutputPath
    ) 'Restart persistence BeforeRestart'

    [ordered]@{
        StateSchema = 2
        TestId = 'OMNIX-RESTART-EVIDENCE-BINDING-STATE-001'
        CreatedUtc = [DateTime]::UtcNow.ToString('o')
        EvidenceBinding = $binding
    } | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $RestartBindingStatePath -Encoding UTF8

    Binding-Summary $binding $Kind $null 'Restart Windows normally, then run Kind=RestartAfter.' | ConvertTo-Json -Depth 5
    exit 0
}

# RestartAfter
$bindingState = Read-Json $RestartBindingStatePath 'Restart evidence binding state'
if ($bindingState.TestId -ne 'OMNIX-RESTART-EVIDENCE-BINDING-STATE-001' -or [int]$bindingState.StateSchema -lt 2) {
    throw 'Restart evidence binding state is invalid or too old for installed payload identity.'
}
$currentBinding = New-OmnixEvidenceBinding -CorePath $CorePath -SourceCommit $SourceCommit
if ([string]$bindingState.EvidenceBinding.SourceCommit -ne [string]$currentBinding.SourceCommit) {
    throw 'OMNIX source commit changed across the Windows restart.'
}
if ([string]$bindingState.EvidenceBinding.CoreSha256 -ne [string]$currentBinding.CoreSha256) {
    throw 'Installed OMNIX.Core.dll changed across the Windows restart.'
}
if ([string]$bindingState.EvidenceBinding.PayloadIdentitySha256 -ne [string]$currentBinding.PayloadIdentitySha256) {
    throw 'Installed OMNIX payload identity changed across the Windows restart.'
}
Remove-ReportIfPresent $OutputPath
Invoke-Child 'reboot-persistence-acceptance.ps1' @(
    '-Phase','AfterRestart',
    '-StatePath',$RestartStatePath,
    '-OutputPath',$OutputPath
) 'Restart persistence AfterRestart'
$restart = Save-BoundReport $OutputPath $currentBinding $startedUtc 'Restart persistence report'
if (-not [bool]$restart.BootSessionChanged) { throw 'Restart report did not prove a changed Windows boot session.' }
Binding-Summary $currentBinding $Kind | ConvertTo-Json -Depth 5
exit 0
