<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <AssemblyName>OMNIX.Core</AssemblyName>
    <RootNamespace>OMNIX.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <Reference Include="System.Security" />
  </ItemGroup>
</Project>
